export const API_DOMAIN = 'https://burfield-voting-app.herokuapp.com';
export const authDomain = 'matthew-burfield.au.auth0.com'
export const audience = 'matthew-burfield.com.au/voting-app'
export const scope = 'openid%20profile%20email'
export const responseType = 'id_token%20token'
export const clientId = '9a0Bi5RDIAHWs8j3hwGJm8EEPR17IIGE'
export const redirectUrl = 'https://matthew-burfield.github.io/FCC-voting-app/login'
export const nonce = '123abc'
export const state = '123abc'
export const noSurvey = { notFound: 'notFound' }